#include <Array.au3>
AutoNotepad()
Func AutoNotepad()
   Run("notepad.exe")
   Local $hWnd = WinGetHandle("[CLASS:Notepad]","")
   WinWaitActive("[CLASS:Notepad]")
   Send("Algum texto aqui...{ENTER}{TAB}")
   Sleep(1000)
   Send("Novamente... ")
   Opt("SendKeyDelay", 50)
   Send("Algum texto aqui...")
   Sleep(1000)
   Opt("SendKeyDelay", 100)
   Send("{BS 20}")
   Sleep(1000)
   Send("^n")
   Sleep(500)
   $hWnd = WinGetHandle("[CLASS:#32770]")
   Local $aPos = WinGetPos($hWnd)
   Local $bPos = ControlGetPos($hWnd, "", "[CLASS:Button; INSTANCE:3]")
   MouseMove($aPos[0]+$bPos[0]+$bPos[2]/2,$aPos[1]+$bPos[1]+$bPos[3]/2+30)
EndFunc